### ISSUE TITLE
Problem on creating a new characteristic

### ISSUE THREAD

**Issue by MonicaMina** [ZEISS-PiWeb/PiWeb-Api#121]
Hello, I have a problem on creating ta new characteristic after creating the part.
I share with you my code. 

1. I have to create new parts for the path "ABC/CD / 10 / AAA". I create 3 InspectionPlanPartDto. First the part "ABC/CD", then the part "10" and finally the part "AAA". They are CORRECLTY generated in piweb.

2. Then I want to create a NEW characteristic for the path "ABC/CD / 10 / AAA / char1" and I try to use this code
![image](https://user-images.githubusercontent.com/77144454/139067891-f8f5b6ea-f074-4eaa-84be-5607b335fa9a.png)
I search for the characteristics save under the parentPath (where parentPath = "ABC/CD / 10 / AAA") and if there is none I try to create my new characteristic in this way
![image](https://user-images.githubusercontent.com/77144454/139068164-f9aeb36c-7f6c-4838-84d5-3ac5176fc817.png)
(where charPath = "ABC/CD / 10 / AAA / char1")

But I got this error
"The parent item with path '/ABC/CD / 10 / AAA' does not exist".

Thanks in advance for your help

**Comment by czthiele** [comment]
The problem is in your `createCharPath` function:
The line `PathHelper.String2CharPathInformation(String.Concat(parentString, PathHelper.DelimiterString, charString, PathHelper.DelimiterString))` uses PathHelper.String2CharPathInformation. This helper method treats every item in the path as a characteristic (thus String2**Char**PathInformation). And of course there is no characteristic with the path ABC/CD/10/AAA/, since these are parts.
Working with the path as a string like this `Dim parentString As String = parentPath.ToString().TrimEnd("/")` can lead to problems, so it is better to directly work with the path as a PathInformationDto.
You could simpy do this to get the correct characteristic path:
`Dim characteristicPath = PathInformationDto.Combine(parentPath, PathHelper.String2CharPathInformation(charString))`
This combines the parent path with a newly created PathInformationDto containing the characteristic, the result would be 
ABC/CD/10/AAA/char1. Escaping etc. is then done by the API nuget.

I hope this solves your problem.

**Comment by MonicaMina** [comment]
It worked! Thank you.
