### ISSUE TITLE
Link to PTX report file with MSEL parameter

### ISSUE THREAD

**Issue by jdunkelmann** [ZEISS-PiWeb/PiWeb-Api#127]
Hi, with means of "shellExecute" I can launch PiWeb Monitor and pass parameters to open a PTX report and use a predefined MSEL file for custom filters. My parameters look something like this:
-open "\\networkshare\MyReport.ptx" -searchCriteria "\\networkshare\MyFilters.msel".
Now, I would like to send mails and embed a link to the same report file and filter. I figured out that there is a "piweb" protocol which leads me to believe that this might be the solution here. Can you confirm that a URL starting with piweb:// can actually do this? And if so, could you explain how the syntax of the URL has to be?

**Comment by czthiele** [comment]
Hi @jdunkelmann,

as far as I know the piweb:// protocol exists to simply open reports but without further parameters. Another possible solution would be to save a temporary report with the modified measurement selection and directly send a link to this file. For this you would open the report using the Cmdmon and the parameters _-searchCriteria <file.msel> -refresh -save <newReport.ptx>_. 

I hope this will help in some way. Otherwise this is more of a question for the regular support, since it is not related to the API.

**Comment by jdunkelmann** [comment]
The report creation cannot be automated because the reports include buttons that need to be clicked in order to select the desired layout. Only after a user (the mail recipient) has clicked one of those buttons, the report will load its data. But, question answered! Thanks Alexander!
