### ISSUE TITLE
No values fetched when part path includes special characters

### ISSUE THREAD

**Issue by jdunkelmann** [ZEISS-PiWeb/PiWeb-Api#216]
Hi,
going from REST API version 1.8 to 1.9, the endpoint _/values_ does not return any values in if the part path includes special characters like "-" or " " and while the characteristicUuids parameter is not specified (empty "characteristics").
This is my request: `GET http://server:8080/dataServiceRest/values?partPath=%2FModel-400&&limitResult=1`
This is the response:
`[
    {
        "characteristics": {
        },
        "uuid": "d2c769ef-3879-4674-b51f-5d787524f777",
        "partUuid": "832c7725-4cb7-4017-b492-4d8ca486c163",
        "lastModified": "2023-05-10T13:19:43.233Z",
        "created": "2020-10-05T09:36:59.817Z",
        "attributes": {
        }
    }
]`

I do get values under "characteristics" if one of the following applies:
- part path does not contain dash or blank or
- server is switched to 1.8 or
- at least one characteistic uuid is specified

Specifying characteristic uuid's is no option because some parts contain up to 3.600 characteristics and we always need all of them.

**Comment by czthiele** [comment]
Hi @jdunkelmann 

this is indeed a strange behaviour. I tried to reproduce it using Postman, but with no success:

![OF9i9YvPd6](https://github.com/ZEISS-PiWeb/PiWeb-Api/assets/51409393/e6a8cd03-9f31-4275-8a54-0bb488c6b6f2)

The server 8.4 with DataService 1.9 seems to produce the correct result, the same as with 1.8 (except the order of the JSON fields).

One potential pitfall could be url encoding. You already encoded the /, but space and dash are also candidates which can be problematic, depending on the used tools.

Please try the following:
- encode dash and space with url encoding
- if you did not try this already, what happens when you use a browser to do this GET request? (with url encoding)

Just for your information, the characteristic uuids outweigh the part path if omitted (or lost in conversion), this could partially explain why this way it is working. But not why it was working with the older API version using the path only and stopped after upgrading. Nevertheless I will take a look at the implementations.

Best regards
czthiele

**Comment by czthiele** [comment]
Hi @jdunkelmann, of course, I would then try to reproduce it with your export.

**Comment by jdunkelmann** [comment]
> Hi @jdunkelmann, of course, I would then try to reproduce it with your export.

"Unexpected error" when trying to export as *.qdb. Could you provide me with a mail address so I can share a SQL Server backup link?

**Comment by czthiele** [comment]
Hi @jdunkelmann, small status update:
I can reproduce the behaviour with your database backup and investigating the cause now.

One workaround for you came to my mind: Instead of using the part path you could also use the part uuid:

_http://server:8080/dataServiceRest/values?partUuids={00000000-0000-0000-0000-000000000000}&limitResult=1_

Just insert the uuid of your part. You can also specify more than one part to search in multiple parts. This way the query has the same complexity, but additionally you do not have to deal with special characters in paths.

I will notify you here when a fix is available.

**Comment by jdunkelmann** [comment]
Thanks Alexander!
I would have to change a lot in our codes. But thanks for the hint.

**Comment by czthiele** [comment]
Good news @jdunkelmann!
The bug should be fixed with service pack 8.4.15. 
Would be great if you can verify it and give us a short feedback. Thanks for reporting this bug!

**Comment by jdunkelmann** [comment]
Tested and approved - thanks, Alexander!
