### ISSUE TITLE
#help wanted# API measurement searchCondition multiple condition

### ISSUE THREAD

**Issue by JiangDayuan** [ZEISS-PiWeb/PiWeb-Api#3]
I'm a application engineer in Zeiss China. And I'm working on a project which need API to get some data from PiWeb.

Here is my problem:
I used the following url to GET the request:
http://10.202.162.122:8090/dataServiceRest/measurements?searchCondition=14In[SH20181220095422]+20002In[Shanghai]
And returned: 'Message': "Conditions must concatenated by '+':,20002In[Shanghai]."

I tried http://10.202.162.122:8090/dataServiceRest/measurements?searchCondition=14In[SH20181220095422] and http://10.202.162.122:8090/dataServiceRest/measurements?searchCondition=20002In[Shanghai] which were both right.

Did I use the wrong method?

Email: fengyuan.jiang@zeiss.com
Max Jiang

**Comment by daniel-lahmann** [comment]
Hello Max Jiang,

sorry for my late reply. 

You need to encode the url. Most characters are recognized correctly without encoding but others are get lost, e.g. '+'. Use instead of '+' url encoded string representation '%2B'.
Please find more about HTML url encoding here: https://www.w3schools.com/tags/ref_urlencode.asp

Best regards,
Daniel Lahmann
