### ISSUE TITLE
RawDataService - Create new object and return key information?

### ISSUE THREAD

**Issue by ThomasFischer1** [ZEISS-PiWeb/PiWeb-Api#47]
**Used version**
5.0.1

_**Interfaces**_
- public Task CreateRawData(RawDataInformation info, byte[] data, ....);
- public Task<RawDataInformation[]> ListRawData(RawDataEntity entity, string[] uuids, FilterCondition filter, ....);
- public Task<byte[]> GetRawData(RawDataTargetEntity target, int rawDataKey, Guid? expectedMd5 = null, ....);

**Question**
Why does the "Create task" function have no return value RawDataInformation?

**Scenario**
If you create a new object with the key -1.

You now have two options to determine the key:
First the data is read again with the "ListRawData" function.
- Now you determine the last key and hope that nobody else has generated data in the meantime.
or
- Use the filter restriction and hope that the filename is unique

Hope I have made a mistake and there is an easier way to solve this

**Comment by czthiele** [comment]
Hi @ThomasFischer1,

unfortunately there is no other way to retrieve the generated raw data key, at least not at the moment. In most scenarios you just want to upload raw data automatically, and when retrieving it later you use ListRawData again, since there is the possibility that someone has overwritten the file using the same key. 
Nevertheless I see the possible benefit of receiving the generated key after creation. I will add the improvement label to this issue, and we will take a look at it, since there are of course some compatibility limitations we have to consider.

I will let you know right here when there is any progress regarding this issue.

**Comment by czthiele** [comment]
With API NuGet 7.1.0 the method CreateRawData will now return RawDataInformation containing the new key.
