### ISSUE TITLE
"Windows" authentication mode

### ISSUE THREAD

**Issue by jdunkelmann** [ZEISS-PiWeb/PiWeb-Api#50]
Hello,
the PiWeb REST manual describes how to get data from the server using the basic authentication mode. 
We now need to connect with a PiWeb server that is configured to use Windows authentication mode (Active Directory). Can you explain how establish connections in Windows mode? Do we just have to pass over the Windows user name without a password?

**Comment by czthiele** [comment]
Hello @jdunkelmann,

this depends on your used HttpClient. You could take a look at issue #29 to find an answer for both our own .NET SDK or the standard C# HttpClient.

Just let me know if this already helps or if you're using another HttpClient/programming language.

**Comment by jdunkelmann** [comment]
We are connecting from a Delphi written application. Authentication methods here include Simple, Basic, OAuth1 and OAuth2.

**Comment by czthiele** [comment]
In this case you have two options, the first is using some kind of library/plugin for Delphi supporting required authentication mode NTLM/Kerberos (in PiWeb ActiveDirectory/Windows). 
Since NTLM/Kerberos is a standardized procedure which is equally implemented in our REST API, your second possibility would be to exactly follow the NTLM-scheme and do the authentication requests step by step yourself (the part which otherwise is done by a HttpClient class).
This could be a little tricky but not impossible.

**Comment by jdunkelmann** [comment]
Hard to believe but I could find any 3rd party Delphi component for this purpose. Can you provide more details on option2?

**Comment by czthiele** [comment]
Trying to explain NTLM/Kerberos in detail would really go beyond the scope of this question, since this is nothing specific to PiWeb but rather a standard which is provided by the used backend service (WCF or ASP.NET for example) on which we have no influence.
I have done a quick search for documentation and found some links that should be helpfull:
[Extensive description of NTLM](http://davenport.sourceforge.net/ntlm.html) including an HTTP example in Appendix B,
[Kerberos documentation](http://web.mit.edu/kerberos/www/krb5-latest/doc/) and
[Example communication using Kerberos](https://medium.com/@robert.broeckelmann/kerberos-wireshark-captures-a-spnego-example-e22e6b1d662a).
It may be helpful to use a client like PiWeb Planner and connect to the destination server, all while recording the traffic behind using for example Fiddler or Wireshark. This way you can analyse what is going on in the background.

Another approach (which is by far easier if you have the possibility) is to create the HttpClient in another programming language which already supports NTLM/Kerberos and calling the resulting .dll in Delphi. 

I hope that this helps you a little bit, it is quite unfortunate that there is no free component for Delphi already supporting this.

**Comment by jdunkelmann** [comment]
Thanks a lot, czthiele! This leaves us with quite some homework. 
Just to be claer: NTLM/Kerberos authentication is part of the client/server communication and PiWeb server only needs the user name after successful authentication to check for PiWeb-specific user rights?

**Comment by czthiele** [comment]
That is correct, once the authentication was successfull PiWeb Server already knows the authenticated user who sent the request, and can check authorization based on their user rights.
