### ISSUE TITLE
Posting a mesaurement with binary data

### ISSUE THREAD

**Issue by JakubWw** [ZEISS-PiWeb/PiWeb-Api#56]
I am having troubles with finding PiWeb Rest API Command for a specific problem.
My PiWeb server version is 7.0.2.0.
Currently my app is using both:

POST /dataServiceRest/measurements
and
POST /rawDataServiceRest/rawData/characteristic

To send measurement and after that send binary data regarding that measurement to other characteristic.
I would like to send all of that data as a single measurement.
It would look like this:

Measurement:
Characteristic 1 Val (5)
Characteristic 2 Val(5)
Characteristic 3 BinData1, BindData2
Characteristic 4 BinData

Notice that I also need to send two binary files at once into a single characteristic.
How can that be accomplished?

**Comment by czthiele** [comment]
Hello @JakubWw, sorry for the late reply.

At first we need to take a look at what you want to accomplish and evaluate if this is possible with PiWeb.
As you stated you want to put your binary data right into your measurement as a measured value of some characteristic, if I understood correctly. This is not possible, since data types for attributes are limited to float, int, string, date and catalog, so you can not create an attribute which is binary data right away.
We have two main services, DataServiceRest for configuration, inspection plan and measurements, and RawDataServiceRest for binary data (in our terms raw data). Because of this separation you wont be able to upload binary data right away with your measurement, instead you need to do it separately (exactly the way you are doing it currently). 
At the moment the RawDataService can only handle POSTs with one binary date at a time, so you still need mutliple POSTs for multiple binaries, there is no batch upload.

I can give you another idea which might help: raw data can be put on any entity, even measured values. For this you would POST your binary file to RawDataServiceRest/rawData/value/MeasurementUuid|CharacteristicUuid. The uuid is in this case a compound key of the measurement uuid and the characteristic uuid, separated by a pipe |. This will post the binary exactly to one measured value in one measurement. 
The screenshot below show this using PiWeb Planner, you can see a measurement and measured values, and you can open the raw data dialog on any measured value. If a characteristic is unmeasured you can enable "Display unmeasured characteristics" in the lower left corner. The same way you can upload your raw data to specified characteristics using the API. This way you have the binary data only in the scope of the measurement. A GET would use the compound uuid too.

![rawdata_value](https://user-images.githubusercontent.com/51409393/99973327-ef228900-2d9f-11eb-885e-2a2ec1ae1f1b.jpg)

I hope this helps, feel free to ask further questions.

**Comment by JakubWw** [comment]
Thank you, you answered my question.
