### ISSUE TITLE
how to fetch measurements with multi conditions

### ISSUE THREAD

**Issue by Mor8** [ZEISS-PiWeb/PiWeb-Api#64]
**Used version**
PiWeb Server: 7.6.5

**Question**
Your detailed question

- What do you want to achieve?
I would like to fetch measurements with multi conditions which means a specific duration of measurement attribute 4.
how should I describe the request?

for example:
part name: metalpart
start date: 2020-11-10T15:00:00Z
end date: 2020-11-19T14:59:59Z

the request would be...
http(s)://[ServerUri:Port]/DataServiceRest/measurements?pathPath=/metalpart&searchCondition=4>=[2020-11-10T15:00:00Z]... 

I tried to use '+' to combine the conditions but it does not work.

**Comment by czthiele** [comment]
Hello @Mor8,

as you already suggested, combining the conditions with a '+' is actually the right way, but in most cases you need to encode this special sign in an URL.
This is highly the reason why this wont work in your case:
.../measurements?pathPath=/metalpart&searchCondition=4>=[2020-11-10T15:00:00Z]+4<=[2020-11-19T14:59:59Z]

But this should work:
.../measurements?pathPath=/metalpart&searchCondition=4>=[2020-11-10T15:00:00Z]**%2B**4<=[2020-11-19T14:59:59Z]

Notice that we encoded the '+' to '%2B'.
Since the URL encoding is only documented shortly on the [general information](http://zeiss-piweb.github.io/PiWeb-Api/general#gi-parameter) page of the documentation, i will add this hint directly to the search conditions.

If hope this solves your problem.

**Comment by Mor8** [comment]
Thank you for the information. it works fine.
