### ISSUE TITLE
Problem on creating a new measurement with k-attribute

### ISSUE THREAD

**Issue by MonicaMina** [ZEISS-PiWeb/PiWeb-Api#67]
Hello, I have a problem on creating a new measurment with k-attribute.
When I  create a measurement, I need to specify the gauge number in a k-attribute. I tried to use the key K12, but it didn't work because the gauge number format is alphanumeric (like "7E910852") while this key expects a number. Our Piweb support contact told me that I should use the key K4072 that is contained into the folder K12, but I don't know how to reach this key from the code.
Thanks in advance

**Comment by czthiele** [comment]
Hello @MonicaMina,

as you already suggested, the attribute K12 is indeed the inspection tool in PiWebs standard configuration, and it is important to mention that this attribute has the data type catalog. This is why it expects a number as its value, which would be the number of the catalog entry.

K4072 is the gauge number, and part of the referenced catalog (inspection tool catalog in this case, which has some more attributes like gauge name K4083). You cannot use this attributes directly when creating measurements.
This is the purpose of catalogs, for example you create a catalog entry for each inspection tool you use, and then simply reference the appropriate entry with its number when creating measurements.

So in your case you need to know if the desired gauge number (e.g. 7E910852) is already present in the catalog. If yes, you need the number of the catalog entry and use this as the value for K12 in your measurement. If not, you can create a new catalog entry (e.g. if the inspection tool is new).

I will give you some examples on how to check if the value is already present:

To get the catalog you can ask the configuration for K12. This will get us an AbstractAttributeDefinitionDto, but since K12 uses a catalog we can cast it to CatalogAttributeDefinitionDto to access the catalogs uuid.

```
var catalogAttribute = ( await dataService.GetConfiguration()).GetDefinition( 12 ) as CatalogAttributeDefinitionDto;
var catalog = await dataService.GetCatalog( catalogAttribute.Catalog );
```

Now you have the inspection tool catalog. It contains catalog entries, each with an array of AttributeDtos(K4072, K4073...) and a value per attribute. Now you need to check if there is any entry where K4072 equals your gauge number 7E910852. Look into each entry, search for attribute K4072, check the value. If you have a match return the key of the catalog entry and use it in your measurement as K12.
If there is no match, you can create a new entry for the catalog using dataService.CreateCatalogEntries(...).

I hope this helps, feel free to ask further questions. I recommend reading the documentation about [configuration](http://zeiss-piweb.github.io/PiWeb-Api/sdk/v6.0/#ba-configuration).
