### ISSUE TITLE
Problem on creating a part with "/" character

### ISSUE THREAD

**Issue by MonicaMina** [ZEISS-PiWeb/PiWeb-Api#80]
Hello, I have a problem on creating a new part that contains the "/" character.
I know this character is used to separate the various folders in a path. Is there a way to avoid that the "/" character is interpreted as the separator for a new folder?
For example, I would like to create the path "CCCC 11/3 SS/operation20/test", where the parts to create are three: 
"CCCC 11/3 SS", 
"operation20",
"test",
but I got an error when I try to create this one "CCCC 11/3 SS" (that contians the "/" char)

Thanks in advance

**Comment by nicoweh** [comment]
Hello MonicaMina,
creating a new part that contains slashes is possible. But it is necessary to escape these special characters with a backslash prefix.
In your example, change "CCCC 11/3 SS/operation20/test" to "CCCC 11\/3 SS/operation20/test".
Please note that backslashes need to be escaped too in some cases (e.g. if you build your own JSON instead of using the SDK). Use "CCCC 11\\/3 SS/operation20/test" in this case.

**Comment by MonicaMina** [comment]
The problem is solved. Thanks
